### PR TITLE
PMM-9379 implemented grafana db type test

### PR DESCRIPTION
**Pull request by vyarosh**

### CODE REVIEW

**Comment by vyarosh** [comment]
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/11342/pipeline

**Comment by puneet0191** [comment]
@vyarosh your job execution fails, please look into it

**Review by puneet0191 — DISMISSED** [review]
check the build

**Comment by vyarosh** [comment]
It's because the DB is "sqlite3" yet

**Comment by puneet0191** [comment]
This has been still not merged, we reverted the Dev changes on this on 2.27.0, hence needs to be waiting for more duration

**Comment by vyarosh** [comment]
https://jira.percona.com/browse/PMM-4466 - ticket is not merged yet

**Review by beatahandzelova — APPROVED** [review]

**Pull request merged**
