### PR TITLE
PMM-9515

### PR DESCRIPTION
**Pull request by vyarosh**
tests to reduce the backlog

### CODE REVIEW

**Comment by puneet0191** [comment]
@vyarosh you have conflicts here, please review them

**Comment by puneet0191** [comment]
@vyarosh here too

**Comment by vyarosh** [comment]
resolved.

**Comment by vyarosh** [comment]
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/17506/pipeline/ - bm test

**Comment by vyarosh** [comment]
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/15841/pipeline/ -upgrade tests

**Review by beatahandzelova — APPROVED** [review]

**Pull request merged**
