### PR TITLE
PMM-9951 Adding integration tests for PGSS

### PR DESCRIPTION
**Pull request by puneet0191**
https://pmm.cd.percona.com/job/pmm2-ui-tests-matrix/801/

### CODE REVIEW

**Review by JiriCtvrtka — APPROVED** [review]

**Comment by puneet0191** [comment]
please review again, attached results.

**Comment by beatahandzelova** [comment]
@puneet0191 Could you please add the test cases numbers as I suggested for tracking purposes? I created them and marked as automated already.

**Comment by puneet0191** [comment]
@beatahandzelova where?

**Comment by puneet0191** [comment]
I mean where did you suggest?, I can't recall

**Comment by beatahandzelova** [comment]
Screenshot from 2022-07-29 15-39-24
In this PR. Is it visible only for me?

**Comment by puneet0191** [comment]
It says pending, you forgot to send this to PR so not visible to me, now please help me change them and merge if this looks okay

**Review by JiriCtvrtka — DISMISSED** [review]

**Review by beatahandzelova — APPROVED** [review]

**Pull request merged**
