### PR TITLE
Update CodeceptJS to version 3.2.2

### PR DESCRIPTION
**Pull request by tiagomotasantos**
During UI Hackathon I worked on e2e tests, one of the things done was to update CodeceptJS to the latest version and Playwright to the version used by this new version of CodeceptJS.

The only change required (breaking change introduced in 3.2.0) was to update the timeout in the config file. Now the global timeout property is in seconds (not in ms) and apparently this property was not working properly before for some tests. Had to use ~~100~~ 200 seconds here as 10 seconds were not enough for some tests. (We should keep an eye on this to update this value if needed)

https://codecept.io/advanced/#timeout
https://codecept.io/changelog/#_3-2-0

https://github.com/Percona-Lab/pmm-submodules/pull/2235

### CODE REVIEW

**Comment by tiagomotasantos** [comment]
As per the report https://pmm.cd.percona.com/job/pmm2-ui-tests/11291/allure/#suites/7cd6353420db44afc4108c7e94fbf4a1/4e6fddb5200eaa82/ Backup tests failed due to reaching the 100s timeout so I'm doubling it.

**Comment by tiagomotasantos** [comment]
Mainly tests related to IA seem to be failing now: https://pmm.cd.percona.com/job/pmm2-ui-tests/11298/allure/#suites/01c7aebf2d5a4e8294c1e113379120cd/ec3bfc02e8c60ad2/
Seems unrelated to this PR though, need to check those. But the problems with the timeout were fixed

**Comment by yurkovychv** [comment]
@tiagomotasantos I've tested a few times. Looks like this one is failing on your branch consistently https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/11366/tests

**Comment by tiagomotasantos** [comment]
@yurkovychv the problem here is with the logic of the test. We are waiting for "MySQL exporter" agent and there's no MySQL exporter in our test container neither by default in PMM. 

I see the following options:

- Try with Postgres exporter or Node exporter since it's by default in pmm server;
- Add MySQL exporter to test container (might still fail locally);
- Remove the test

I prefer the first solution. What do you suggest? Maybe you know why this was working before and not now or have a better solution

**Comment by tiagomotasantos** [comment]
@yurkovychv solved it in a different way: by using add instance API to add MySQL instance at the beginning of the test. Now every test passes!

**Review by fabio-silva — APPROVED** [review]

**Comment by puneet0191** [comment]
@tiagomotasantos I have looked, seems good to me, just trying to understand why nightly failed, I have asked @vyarosh to help look into it.

**Review by puneet0191 — DISMISSED** [review]

**Comment by vyarosh** [comment]
@tiagomotasantos , @puneet0191  the issue is the following:
`https://github.com/percona/pmm-ui-tests/blob/codecept-3.2.2/tests/dashboards/pages/searchDashboardsModal.js#L118` this method is called with undefined argument in test here: `https://github.com/percona/pmm-ui-tests/blob/codecept-3.2.2/tests/dashboards/verifySearchDashboards_test.js#L37`
I'm tying to findout why

**Comment by vyarosh** [comment]
Fixed. The access model to the 'current' object has been changed. Adjusted test accordingly.

**Review by vyarosh — APPROVED** [review]

**Pull request merged**
