### PR TITLE
PMM-10053 tests to cover --credentials-source

### PR DESCRIPTION
**Pull request by puneet0191**

### CODE REVIEW

**Review by VoK0 — APPROVED** [review]
Ok !

**Comment by peterSirotnak** [comment]
Not all tests are passing in pmm-ui-tests. Can you take a look at it?
https://pmm.cd.percona.com/job/pmm2-ui-tests/17647/allure/#suites/2de406ea63a43f8ca51fa04e34f37003

**Comment by puneet0191** [comment]
thanks Peter, it seems like a bug in the development code, I have logged an issue for developer, lets keep this open until they fix it

**Comment by peterSirotnak** [comment]
Is bug that was blocking this fixed?

**Comment by puneet0191** [comment]
I am working on fixing and modifying these, keep this open

**Pull request closed without merging**
