### PR TITLE
PMM-10311 Ability to initialize the /srv directory when bootstrapping PMM Server

### PR DESCRIPTION
**Pull request by peterSirotnak**
https://pmm.cd.percona.com/job/pmm2-ui-tests/19050/allure/#suites/9d5f32385ffe5c6a6eae9fa2e8d22fe9/9d87fa9da50f184e/

### CODE REVIEW

**Comment by puneet0191** [comment]
@peterSirotnak resolve conflicts on this one

**Comment by puneet0191** [comment]
@peterSirotnak thisis ready?

**Comment by peterSirotnak** [comment]
> @peterSirotnak thisis ready?

 Yes I added new tag and selecting pmm server version

**Comment by puneet0191** [comment]
@peterSirotnak the same here, After changing the base branch to main we have conflicts

**Review by puneet0191 — CHANGES_REQUESTED** [review]
conflicts

**Comment by puneet0191** [comment]
I have run the tests and they are failing @peterSirotnak https://pmm.cd.percona.com/job/pmm2-ui-tests/19723/allure/#suites/9d5f32385ffe5c6a6eae9fa2e8d22fe9/98e755ba071dabca/

**Comment by peterSirotnak** [comment]
Latest Jenkins run:
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/20914/pipeline/

**Review by puneet0191 — DISMISSED** [review]

**Pull request merged**
